# Generated by Django 4.0.6 on 2022-07-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_userprofile_default_postcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
