# Generated by Django 3.1.4 on 2020-12-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='name',
            field=models.CharField(default='Fara nume', max_length=256),
        ),
    ]
