# Generated by Django 3.1.4 on 2020-12-30 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0003_auto_20201229_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size_quantity_available',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wines.size'),
        ),
        migrations.AlterField(
            model_name='size_quantity_sold',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wines.size'),
        ),
    ]
