# Generated by Django 3.1.4 on 2021-02-14 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0004_auto_20201230_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='size_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_available', models.IntegerField(default=0)),
                ('qty_sold', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wines.size')),
            ],
            options={
                'verbose_name': 'Cantitate disponibila per dimensiune dimensiune',
                'verbose_name_plural': 'Cantitate disponibila per dimensiune dimensiune',
            },
        ),
        migrations.RemoveField(
            model_name='size_quantity_sold',
            name='size',
        ),
        migrations.RemoveField(
            model_name='size_quantity_sold',
            name='wine',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='only_for_admin',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='price',
        ),
        migrations.DeleteModel(
            name='size_quantity_available',
        ),
        migrations.DeleteModel(
            name='size_quantity_sold',
        ),
        migrations.AddField(
            model_name='size_details',
            name='wine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wines.wine'),
        ),
    ]
