# Generated by Django 4.0.6 on 2022-07-12 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0005_auto_20210214_1235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size_details',
            options={'verbose_name': 'Dimensiune', 'verbose_name_plural': 'Dimensiuni'},
        ),
        migrations.AlterField(
            model_name='wine',
            name='first_time_listed',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
