# Generated by Django 4.0.6 on 2022-09-21 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0007_translation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translation',
            name='color',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='grape',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='region',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='aging',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='boxing',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='color_details',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='palate',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='serving',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='vinification',
        ),
        migrations.AlterField(
            model_name='translation',
            name='wine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wines.wine'),
        ),
    ]
