# Generated by Django 4.0.6 on 2022-09-21 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0008_remove_translation_color_remove_translation_grape_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translation',
            name='wine',
        ),
    ]
