# Generated by Django 4.0.6 on 2022-09-21 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0009_remove_translation_wine'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='wine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wines.wine'),
        ),
    ]
