# Generated by Django 4.0.6 on 2022-08-13 11:28

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_original_bag_order_stripe_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='adresa',
            field=models.CharField(max_length=255, verbose_name='adresa'),
        ),
        migrations.AlterField(
            model_name='order',
            name='adresa_linia_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='adresa_linia_2'),
        ),
        migrations.AlterField(
            model_name='order',
            name='judet',
            field=models.CharField(max_length=50, verbose_name='judet'),
        ),
        migrations.AlterField(
            model_name='order',
            name='nume',
            field=models.CharField(max_length=50, verbose_name='nume'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tara',
            field=django_countries.fields.CountryField(default='RO', max_length=2, verbose_name='tara'),
        ),
        migrations.AlterField(
            model_name='order',
            name='telefon',
            field=models.CharField(max_length=25, verbose_name='telefon'),
        ),
    ]
