# Generated by Django 4.0.6 on 2022-08-13 11:40

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_alter_order_adresa_alter_order_adresa_linia_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='adresa',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='adresa_linia_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='judet',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='nume',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='tara',
            field=django_countries.fields.CountryField(default='RO', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='telefon',
            field=models.CharField(max_length=25),
        ),
    ]
