# Generated by Django 3.1.4 on 2021-01-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='on_going',
            field=models.BooleanField(default=True),
        ),
    ]
