# Generated by Django 3.1.4 on 2021-01-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offer_on_going'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
