# Generated by Django 3.1.4 on 2021-01-07 16:05

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_offer_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='text_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
    ]
