# Generated by Django 3.1.4 on 2020-12-26 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='grape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='wine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vinification', models.TextField(blank=True, null=True)),
                ('aging', models.TextField(blank=True, null=True)),
                ('color_details', models.TextField(blank=True, null=True)),
                ('palate', models.TextField(blank=True, null=True)),
                ('serving', models.TextField(blank=True, null=True)),
                ('boxing', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('first_time_listed', models.DateField(auto_now=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('only_for_admin', models.BooleanField(default=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.color')),
                ('grape', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.grape')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.region')),
            ],
        ),
        migrations.CreateModel(
            name='size_quantity_sold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.size')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.wine')),
            ],
        ),
        migrations.CreateModel(
            name='size_quantity_available',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.size')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.wine')),
            ],
        ),
    ]
