# Generated by Django 3.1.4 on 2020-12-26 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size_quantity_available',
            name='size',
        ),
        migrations.RemoveField(
            model_name='size_quantity_available',
            name='wine',
        ),
        migrations.RemoveField(
            model_name='size_quantity_sold',
            name='size',
        ),
        migrations.RemoveField(
            model_name='size_quantity_sold',
            name='wine',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='color',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='grape',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='region',
        ),
        migrations.DeleteModel(
            name='color',
        ),
        migrations.DeleteModel(
            name='grape',
        ),
        migrations.DeleteModel(
            name='region',
        ),
        migrations.DeleteModel(
            name='size',
        ),
        migrations.DeleteModel(
            name='size_quantity_available',
        ),
        migrations.DeleteModel(
            name='size_quantity_sold',
        ),
        migrations.DeleteModel(
            name='wine',
        ),
    ]
